
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>

<main>
        <section class="section3">
            <a href="" class="bleu">Accueil</a> /
            <a href="" class="bleu">Jeux-Vidéos</a> /
            <a href="" class="gris">Les nouveautés de Tétris 64</a>
        </section>
        <div class="d-flex">
            <div class="container1 w-50">
                <section class="section4">
                    <div class="titre">
                        <h3><?= $post['Title'] ?></h3>
                        <p class="pt-3">Dans la catégorie: <span><?= $post['Name'] ?></span> </p>
                        <p>Rédigé par <?= $post['FirstName'] ?><?= $post['LastName'] ?> <?= $post['CreationTimestamp'] ?></p>
                    </div>
                    <div class="article">
                        <p class="pt-3"> <?= $post['Contents'] ?></p>
                    </div>
                </section>
            </div>
            <div class="container2 w-50">
                <hr>
                <h4>Liste des commentaire (1)</h4>
                <!-- Liste des commentaires de l'article du blog -->
                <ul class="comment-list">
                    <?php foreach ($comments as $comment) : ?>
                        <li class="comment">
                            <h5 class="text-white"><i class="fa fa-comment"></i> Rédigé par <?= $comment['NickName'] ?></h5>
                            <article class="text-white-50"><?= $comment['Contents'] ?></article>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <hr>
                <form class="generic-form p-3" action="add_comment.php" method="POST">
                    <input type="hidden" name="postId" value="<?= $post['Id'] ?>">

                    <fieldset >
                        <legend>Nouveau commentaire</legend>
                        <ul class="p-5">
                            <li>
                                <label for="nickName" class="w">Pseudo :</label>
                                <input type="text" id="nickName" name="nickName" class="w">
                            </li>
                            <li>
                                <label class="textarea w" for="contents">Commentaire :</label>
                                <textarea id="contents" name="contents" rows="5" class="textarea w"></textarea>
                            </li>
                            <li class="w1">
                                <button class="button btn btn-dark" type="submit">Ajouter</button>
                                <a class="btn btn-secondary" href="index.php">Annuler</a>
                            </li>
                        </ul>
                    </fieldset>
                </form>
            </div>
        </div>
</main>
