<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="css/admin.css" type="text/css">
</head>

<main>
    <section class="section3">
        <a href="" class="noir">Administration</a> /
        <a href="" class="bleu">Gestion des articles</a> /
        <a href="" class="gris">Créer un nouvel article</a>
    </section>

    <div class="containerAll">

        <div class="leftDiv">

            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <button class="nav-link active" id="v-pills-home-tab" data-toggle="pill" data-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true"><i class="fas fa-newspaper"></i>Gestion des articles</button>
                <button class="nav-link nav" id="v-pills-profile-tab" data-toggle="pill" data-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false"><i class="fas fa-tags"></i>Gestion des catégories</button>
                <button class="nav-link nav" id="v-pills-messages-tab" data-toggle="pill" data-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false"><i class="fas fa-users"></i>Gestion des auteurs</button>
            </div>

        </div>

        <div class="rightDiv">

            <h2>Rédiger un article</h2>

            <form class="needs-validation" action="index.php?page=post&action=add" method="POST" enctype="multipart/form-data">
                <div class="form-row">

                    <div class="col-md-6 mb-3">

                        <label for="validationCustom01">Catégorie de l'article</label>
                        <select class="custom-select" id="validationCustom04" required name="categoryId">
                            <option value=""></option>
                        <?php foreach($categories as $categorie): ?>    
                            <option value="<?= $categorie['Id'] ?>"><?= $categorie['Name'] ?></option>
                        <?php endforeach ?>
                        </select>

                    </div>

                    <div class="col-md-6 mb-3">

                        <label for="validationCustom02">Auteur</label>
                        <select class="custom-select" id="validationCustom04" required name="authorId">
                            <option value=""></option>
                        <?php foreach($authors as $author): ?>    
                            <option value="<?= $author['Id'] ?>"><?= $author['FirstName'] ?> <?= $author['LastName'] ?></option>
                        <?php endforeach ?>
                        </select>

                    </div>

                </div>

                <div class="form-row">

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Titre de l'article</label>
                        <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Saisir un titre évocateur" name="title">
                    </div>

                </div>

                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Texte de l'article</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="content"></textarea>
                </div>



                <div>
                <input type="file" name="fileToUpload" id="fileToUpload">
                </div>

                <a href=""><button class="btn btn-primary" type="submit">Enregistrer</button></a>
            </form>

        </div>

    </div>
</main>
